[package]
name = "lsrt_new"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fibonacii-heap = "0.1.2"
sscanf = "0.4.1"
