name: Unit Tests

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Compile Tests
        run: |
          mkdir test/bin
          make test

      - name: Run Tests
        run: |
          error=0
          for test in test/bin/*; do
            valgrind --leak-check=full --error-exitcode=1 --show-leak-kinds=all --errors-for-leak-kinds=all $test
            if [ $? -ne 0 ]; then
              error=1
            fi
          done
          exit $error
