name: Unit Tests

on:
  push:
    branches:
      - main
      - dev_ivan_cgraph

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Compile Tests
        run: |
          mkdir test/bin
          make test

      - name: Run Tests
        run: |
          bash run_tests.sh
